INSERT INTO CLASSIFICA (USERNAME, TEMPO) VALUES ('user1', TIME '18:45:00');
INSERT INTO CLASSIFICA (USERNAME, TEMPO) VALUES ('user5', TIME '6:00:00');
INSERT INTO CLASSIFICA (USERNAME, TEMPO) VALUES ('user3', TIME '12:15:00');
INSERT INTO CLASSIFICA (USERNAME, TEMPO) VALUES ('user5', TIME '23:00:00');
INSERT INTO CLASSIFICA (USERNAME, TEMPO) VALUES ('user3', TIME '22:15:00');