INSERT INTO CLASSIFICA (USERNAME, TEMPO) VALUES ('user1', TIME '18:45:00');
INSERT INTO CLASSIFICA (USERNAME, TEMPO) VALUES ('user2', TIME '15:30:00');
INSERT INTO CLASSIFICA (USERNAME, TEMPO) VALUES ('user3', TIME '12:15:00');
INSERT INTO CLASSIFICA (USERNAME, TEMPO) VALUES ('user4', TIME '04:50:00');
INSERT INTO CLASSIFICA (USERNAME, TEMPO) VALUES ('user5', TIME '21:00:00');