INSERT INTO CLASSIFICA (USERNAME, TEMPO) VALUES ('Mario', TIME '00:32:34');
INSERT INTO CLASSIFICA (USERNAME, TEMPO) VALUES ('Giovanni', TIME '00:07:25');
INSERT INTO CLASSIFICA (USERNAME, TEMPO) VALUES ('Roberta', TIME '01:02:13');
INSERT INTO CLASSIFICA (USERNAME, TEMPO) VALUES ('Luigi', TIME '00:54:12');
INSERT INTO CLASSIFICA (USERNAME, TEMPO) VALUES ('Morgana', TIME '00:15:42');